### ISSUE TITLE
DNS resolution failure causing Cookie "_oauth2_proxy" not present

### ISSUE THREAD

**Issue by mtucker502** [a5huynh/oauth2_proxy#18]
When I access test.basement.netzolt.com I am prompted to login to github and after logging in I receive an Internal Server 500 error and it appears to be DNS related as the container cannot lookup github.com. 

**Here is the docker stack:**
```
version: "3"
services:
  web:
    image: emilevauge/whoami
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:whoamistack.basement.netzolt.com

  web2:
    image: emilevauge/whoami
    networks:
      - traefik_public

  web2_proxy:
    image: a5huynh/oauth2_proxy
    env_file : /mnt/vault/docker/config/test/test.env
    dns_search: basement.netzolt.com
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:test.basement.netzolt.com
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /mnt/vault/docker/config/autopirate/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://web2:80
      -redirect-url=https://test.basement.netzolt.com
      -http-address=http://0.0.0.0:4180
      -email-domain=netzolt.com
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.111.0/24
```

**Here are the logs from the container:**
```
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 172.16.200.75 - - [18/May/2018:15:41:40 +0000] test.basement.netzolt.com GET - "/oauth2/callback?code=XXXXXXXXXXXXXXXXXX&state=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" 500 331 20.002
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 2018/05/18 15:42:00 oauthproxy.go:527: 172.16.200.75:54382 error redeeming code Post https://github.com/login/oauth/access_token: dial tcp: lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:36175->127.0.0.11:53: i/o timeout
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 2018/05/18 15:42:00 oauthproxy.go:349: ErrorPage 500 Internal Error Internal Error
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 2018/05/18 15:42:00 oauthproxy.go:527: 172.16.200.75:54380 error redeeming code Post https://github.com/login/oauth/access_token: dial tcp: lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:36175->127.0.0.11:53: i/o timeout
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 2018/05/18 15:42:00 oauthproxy.go:349: ErrorPage 500 Internal Error Internal Error
whoami_web2_proxy.1.dkgadr0p8a4w@docker02    | 2018/05/18 15:42:00 oauthproxy.go:602: 172.16.200.75:54382 Cookie "_oauth2_proxy" not present
```

**You can see resolution is broken inside the container:**
```
spider@docker02:~$ docker exec -it 03b9db7e85d4 sh
/ # ping google.com
ping: bad address 'google.com'
```

**However it appears the defined nameserver does work for discovery of other containers in the stack:**
```
/ # cat /etc/resolv.conf
search basement.netzolt.com
nameserver 127.0.0.11
options ndots:0

# ping 127.0.0.11
PING 127.0.0.11 (127.0.0.11): 56 data bytes
64 bytes from 127.0.0.11: seq=0 ttl=64 time=0.073 ms
64 bytes from 127.0.0.11: seq=1 ttl=64 time=0.082 ms
^C
--- 127.0.0.11 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.073/0.077/0.082 ms

/ # nslookup web2
nslookup: can't resolve '(null)': Name does not resolve

Name:      web2
Address 1: 172.16.200.29
```

**However other tests show external resolution fails:**
```
/ # nslookup github.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'github.com': Try again

/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=58 time=7.384 ms
64 bytes from 8.8.8.8: seq=1 ttl=58 time=7.675 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 7.384/7.529/7.675 ms
/ # nslookup github.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8

nslookup: can't resolve 'github.com': Try again
/ #
```
